### PR TITLE
Load track with Once to not WaitGroup.Done twice

### LINKED ISSUE #11: Getting 'negative WaitGroup counter' when Track.Wait
Sometimes when waiting for a track `track.Wait()` I get this panic:

	...
	playlistcontainer loaded
	playlist container loaded
	panic: sync: negative WaitGroup counter

	goroutine 7 [running, locked to thread]:
	sync.(*WaitGroup).Add(0xc2080384c0, 0xffffffffffffffff)
		/usr/lib/go/src/sync/waitgroup.go:67 +0x96
	sync.(*WaitGroup).Done(0xc2080384c0)
		/usr/lib/go/src/sync/waitgroup.go:85 +0x31
	github.com/op/go-libspotify/spotify.(*Track).cbUpdated(0xc2080384b0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1788 +0x4c
	github.com/op/go-libspotify/spotify.(*Session).sendUpdates(0xc208092000, 0xc208092098, 0xc208038570)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:959 +0xb6
	github.com/op/go-libspotify/spotify.(*Session).cbMetadataUpdated(0xc208092000)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:980 +0x4a
	github.com/op/go-libspotify/spotify.sessionCall(0x7feea4079b70, 0x636848)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:185 +0x3b
	github.com/op/go-libspotify/spotify.go_metadata_updated(0x7feea4079b70)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1115 +0x34
	github.com/op/go-libspotify/spotify._Cfunc_sp_session_process_events(0x7feea4079b70, 0xc208055e30, 0x0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/:905 +0x43
	github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc208092000)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:878 +0xd6
	github.com/op/go-libspotify/spotify.func·001()
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x141
	created by github.com/op/go-libspotify/spotify.NewSession
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x819

	goroutine 6 [runnable]:
	sync.(*WaitGroup).Wait(0xc2080384c0)
		/usr/lib/go/src/sync/waitgroup.go:132 +0x169
	github.com/op/go-libspotify/spotify.(*Track).Wait(0xc2080384b0)
		/home/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1793 +0x38
	github.com/fabiofalci/sconsify/sconsify.ToSconsifyTrack(0xc2080384b0, 0xc2080384b0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/track.go:26 +0x33
	github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc2080107e0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:172 +0x208
	github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc2080107e0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:135 +0x28
	github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc2080107e0, 0x0, 0x0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:109 +0x122
	github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc20802a2ca, 0xa, 0xc20800a8f8, 0x8, 0x8, 0xc20801e7e0, 0xc20800a860, 0x0, 0x0)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:47 +0x1ea
	github.com/fabiofalci/sconsify/spotify.Initialise(0xc20802a2ca, 0xa, 0xc20800a8f8, 0x8, 0x8, 0xc20801e7e0, 0xc20800a860)
		/home/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:26 +0x81
	created by main.main
		/home/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:36 +0x26a

After some debugging I can see the follow behavior when things go right when loading one Track at the time:

* Track is being loaded by `newTrack`
* My code calls `track.Wait()` and gets blocked
* `cbUpdated` will be called when `cbMetadataUpdated` gets updates. If track is loaded then `WaitGroup.Done()` , else do nothing (waiting for more update)
* When `WaitGroup.Done()` then `track.Wait()` will get unblocked

And when I get the panic:

* Track is being loaded by `newTrack`
* My code calls `track.Wait()` and gets blocked
* `cbUpdated` is called then `WaitGroup.Done()`
* `cbUpdated` is called then `WaitGroup.Done()`. Here it panics.

The problem is that `cbUpdated` is called twice and in both the track is already loaded so it calls `WaitGroup` to unblock `Wait` but `WaitGroup.Add(1)` is called only once by `newTrack` so only one call is expected. 

I'll try to understand more about this issue but if I'm missing something please let me know.

Thanks

### PR DESCRIPTION
**Pull request by fabiofalci**
Please evaluate.
Still trying to think in how to write tests for these kind of things.

Fixes #11

### CODE REVIEW

**Comment by op** [comment]
Looks good to me. Doesn't the same happen for other data as artist or album?

**Comment by fabiofalci** [comment]
No, that's odd right, only for Tracks.

Anyway I'll keep an eye open on this now and if I see a panic then it's another data struct.

**Comment by op** [comment]
OK, that's interesting. I wonder if this has something to do with metadata coming from multiple sources, eg. only from loading the specific track vs. loading a whole album. Thanks!

**Comment by fabiofalci** [comment]
Yeah, could be.
I tried to make the loading sequential. First the playlist, then the individual track and then the track artist.
https://github.com/fabiofalci/sconsify/blob/master/spotify/spotify_playlists.go#L26

But still got the error from time to time.

**Pull request merged**
